### ISSUE TITLE
batchszie 在4以下不能运行

### ISSUE THREAD

**Issue by Lingwcy** [Henryjiepanli/DBBANet#3]
python train.py --batchsize 2 --model_name DBBANet --gpu_id 0

D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
USE GPU 0
Start Training!
Training  DBBANet  on  FarmSeg  with segclass:  2
Use  test  as the Validation data
Learning rate:  0.0001
  0%|                                                                                                                                                                                               | 0/1042 [00:00<?, ?it/s]D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet50_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet50_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
D:\conda\envs\deeplab\lib\site-packages\torch\nn\functional.py:4373: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1041/1042 [02:34<00:00,  6.75it/s]
Traceback (most recent call last):
  File "train.py", line 568, in <module>
    train_loss, val_iou =  train(train_loader, val_loader, net, Eva_train, Eva_val, criterion, optimizer, 0, opt, epoch)
  File "train.py", line 344, in train
    output = net(X)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 706, in forward
    edge_out,_ = self.decoder_edge(x4,x1)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 643, in forward
    out_32x_ppm =self.ppm(out_32x)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 195, in forward
    priors = [F.interpolate(input=stage(feats), size=(h, w), mode='bilinear', align_corners=True) for stage in
  File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 195, in <listcomp>
    priors = [F.interpolate(input=stage(feats), size=(h, w), mode='bilinear', align_corners=True) for stage in
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 219, in forward
    input = module(input)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\batchnorm.py", line 176, in forward
    return F.batch_norm(
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\functional.py", line 2510, in batch_norm
    _verify_batch_size(input.size())
  File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\functional.py", line 2478, in _verify_batch_size
    raise ValueError(f"Expected more than 1 value per channel when training, got input size {size}")
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])

**Comment by Henryjiepanli** [comment]
这个应该是训练集数据整除batchsize后余数为1，无法正则化，需要改一下batchsize

----- Original Message -----
From: 过风ovo ***@***.***>
To: Henryjiepanli/DBBANet ***@***.***>
Cc: Subscribed ***@***.***>
Sent: Mon, 30 Dec 2024 20:41:03 -0800
Subject: [Henryjiepanli/DBBANet] batch size 在4以下不能运行 (Issue #3)



python train.py --batchsize 2 --model_name DBBANet --gpu_id 0

D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=ResNet50_Weights.IMAGENET1K_V1. You can also use weights=ResNet50_Weights.DEFAULT to get the most up-to-date weights.
warnings.warn(msg)
D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=ResNet50_Weights.IMAGENET1K_V1. You can also use weights=ResNet50_Weights.DEFAULT to get the most up-to-date weights.
warnings.warn(msg)
USE GPU 0
Start Training!
Training DBBANet on FarmSeg with segclass: 2
Use test as the Validation data
Learning rate: 0.0001
0%| | 0/1042 [00:00<?, ?it/s]D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=ResNet50_Weights.IMAGENET1K_V1. You can also use weights=ResNet50_Weights.DEFAULT to get the most up-to-date weights.
warnings.warn(msg)
D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
warnings.warn(
D:\conda\envs\deeplab\lib\site-packages\torchvision\models_utils.py:223: UserWarning: Arguments other than a weight enum or None for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing weights=ResNet50_Weights.IMAGENET1K_V1. You can also use weights=ResNet50_Weights.DEFAULT to get the most up-to-date weights.
warnings.warn(msg)
D:\conda\envs\deeplab\lib\site-packages\torch\nn\functional.py:4373: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
warnings.warn(
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊| 1041/1042 [02:34<00:00, 6.75it/s]
Traceback (most recent call last):
File "train.py", line 568, in
train_loss, val_iou = train(train_loader, val_loader, net, Eva_train, Eva_val, criterion, optimizer, 0, opt, epoch)
File "train.py", line 344, in train
output = net(X)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in call_impl
return forward_call(*args, **kwargs)
File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 706, in forward
edge_out, = self.decoder_edge(x4,x1)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 643, in forward
out_32x_ppm =self.ppm(out_32x)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 195, in forward
priors = [F.interpolate(input=stage(feats), size=(h, w), mode='bilinear', align_corners=True) for stage in
File "C:\Users\ling\Desktop\ieee-trans\A_Comprehensive_Deep-Learning_Framework_for_Fine-Grained_Farmland_Mapping_From_High-Resolution_Images\DBBANet-master\network\DBBANet\model.py", line 195, in
priors = [F.interpolate(input=stage(feats), size=(h, w), mode='bilinear', align_corners=True) for stage in
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\container.py", line 219, in forward
input = module(input)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
return forward_call(*args, **kwargs)
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\modules\batchnorm.py", line 176, in forward
return F.batch_norm(
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\functional.py", line 2510, in batch_norm
_verify_batch_size(input.size())
File "D:\conda\envs\deeplab\lib\site-packages\torch\nn\functional.py", line 2478, in _verify_batch_size
raise ValueError(f"Expected more than 1 value per channel when training, got input size {size}")
ValueError: Expected more than 1 value per channel when training, got input size torch.Size([1, 256, 1, 1])
